#!/bin/sh

dos2unix  *.tex *.bib *.sty *.cls

TMP=$(mktemp /tmp/a.XXXXXX)
[ $? -ne 0 ] && exit 2
for i in *.tex *.bib *.sty *.cls ; do
    iconv -f windows-1250 -t utf8 "$i"  > "$TMP" && mv "$i" "$i".bak && cat "$TMP" > "$i" 
done

